name: Log4j Vulnerability Scanner
description: Scan a directory for Log4j vulnerabilities.
inputs:
  directory:
    description: 'The directory to scan for vulnerabilities.'
    required: true
    default: '.'
runs:
  using: 'composite'
  steps:
    - name: Checkout Log4jDeepScanAction
      uses: actions/checkout@v2
      with:
        repository: UMCSResearchLog/Log4jDeepScanAction
        path: log4j-deep-scan-action  # Path to clone the repository
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        cd log4j-deep-scan-action
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash
    - name: run ls
      run: ls
    - name: Run Log4j Scanner
      run: |
        cd log4j-deep-scan-action/src
        python main.py ${{ inputs.directory }}
      shell: bash
branding:
  icon: 'shield'
  color: 'red'
